"""add predicted_category and confidence to project_images

Revision ID: 75c5f4eb4fe8
Revises: 9a791cba3aae
Create Date: 2026-08-07 23:55:03.552171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75c5f4eb4fe8'
down_revision: Union[str, None] = '9a791cba3aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_images', sa.Column('predicted_category', sa.String(), nullable=True))
    op.add_column('project_images', sa.Column('predicted_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_images', 'predicted_confidence')
    op.drop_column('project_images', 'predicted_category')
    # ### end Alembic commands ###
