"""add scope_of_work to project_analyses

Revision ID: 9a791cba3aae
Revises: a31b204a5901
Create Date: 2026-08-06 15:59:22.749881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a791cba3aae'
down_revision: Union[str, None] = 'a31b204a5901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_analyses', sa.Column('scope_of_work', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_analyses', 'scope_of_work')
    # ### end Alembic commands ###
