"""add contractor_id to projects for multi-tenancy

Revision ID: a31b204a5901
Revises: 794f36360b3b
Create Date: 2026-08-04 21:27:43.227639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a31b204a5901'
down_revision: Union[str, None] = '794f36360b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('contractor_id', sa.UUID(as_uuid=False), nullable=False))
    op.create_index(op.f('ix_projects_contractor_id'), 'projects', ['contractor_id'], unique=False)
    op.create_foreign_key(None, 'projects', 'users', ['contractor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_contractor_id'), table_name='projects')
    op.drop_column('projects', 'contractor_id')
    # ### end Alembic commands ###
